name: gemma_kinetic
description: Robotics Powered by Gemma 4

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter_dotenv: ^5.2.1

  speech_to_text: ^7.3.0
  http: ^1.6.0

  flutter:
    sdk: flutter

  # File picker for resume PDF upload
  file_picker: ^8.0.0

  # Icons
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

flutter:
  assets:
    - .env